// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bduvgohabpcmredidmxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkdXZnb2hhYnBjbXJlZGlkbXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzE0NDIsImV4cCI6MjA2MzUwNzQ0Mn0.tQw6DQlv941T27ns1NnSPBRwHW2HUYtsxsYiJf2eosE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);